CREATE TABLE MEMBER(
	ID VARCHAR2(30 BYTE) PRIMARY KEY, 
	PW VARCHAR2(30 BYTE) NOT NULL, 
	EMAIL VARCHAR2(30 BYTE) NOT NULL, 
	TEL VARCHAR2(30 BYTE) NOT NULL, 
	INTERESTS VARCHAR2(100 BYTE) NOT NULL, 
	JOB VARCHAR2(30 BYTE) NOT NULL, 
	AGE NUMBER NOT NULL, 
	INTRODUCE VARCHAR2(200 BYTE), 
	REGDATE TIMESTAMP NOT NULL
);


DROP TABLE MEMBER;

select * from MEMBER;

Select id from member where id = 'nigael' and pw = '!@12qwaszx';
